COLOR_BG_MAIN = "#0b0e11"
COLOR_BG_PANEL = "#181a20"
COLOR_TEXT_MAIN = "#eaecef"
COLOR_TEXT_SUB = "#848e9c"
COLOR_GREEN = "#0ecb81"
COLOR_RED = "#f6465d"
COLOR_ACTIVE = "#2962ff"
COLOR_BTN_DEFAULT = "#2b3139"
COLOR_BORDER = "#2b3139"

FONT_UNIFIED = ("Consolas", 12)
FONT_BOLD = ("Roboto", 13, "bold")
SIDE_PAD = 15

ROW_LIMIT = 10
SIDEBAR_WIDTH = 260

DEFAULT_COINS = ["BTC", "ETH", "SOL", "BNB", "ADA", "XRP", "DOGE"]
DEFAULT_SYMBOL = "BTC"
DEFAULT_PAIR = "BTCUSDT"
DEFAULT_INTERVAL = "1h"
